### PR TITLE
Added support for configuring webpack's devServer options for client build

### PR DESCRIPTION
**Pull request by s-KaiNet**
Based on the related #248 discussion: 

1. Changed the default overlay configuration for the client dev-server to report only errors.
2. Added ability to specify `devServer` options through the `webpack.config.js`. 

I had to add a new dependency `lodash.merge` (full `lodash` is quite big thus added only needed method). `devServer` options contain some nested properties, that's why native TypeScript features like object spread or object assign will not work (they perform only shallow copy). lodash instead performs deep merge for nested properties.

### CODE REVIEW

**Comment by wictorwilen** [comment]
Can we add some documentation on how to use this? Also how to do it conditional in the webpack config file with something like:

``` JavaScript
...
devServer: debug ? {
	// developer override for the devServer
} : undefined
```

**Comment by s-KaiNet** [comment]
Where would be the best place to add documentation to?

**Comment by pschaeflein** [comment]
It is still not clear to me where I make configuration changes for webpack devServer? The webpack.config.js file is not the simplest file to understand, certainly to new-to-node folks. I had proposed a devServer readme - I think those details should be included, in addition to documenting this new config option.

https://github.com/pnp/generator-teams/compare/preview...pschaeflein:preview?expand=1#diff-b3edc95f0de0070739b77bc93e046d16b7517fce0483891e13f52d042ec9bd48

Also, I would like the dev server to report that it is starting a re-bundle, just like the gulp tasks do. That was in my proposed solution.

 https://github.com/pnp/generator-teams/compare/preview...pschaeflein:preview?expand=1#diff-8e8d76b981e642d14700cc22c8f51219a9ed1aa380b9d36db3e85e7fc2cf9a2b


(I have no idea how this review thing works. Sorry for the extra comment.)

**Comment by s-KaiNet** [comment]
@pschaeflein `devServer` is a part of the standard webpack's [configuration](https://webpack.js.org/configuration/dev-server/), thus for me, it's more natural to provide `devServer` settings inside the `webpack.config.js` rather than creating new files with a special name inside the project root. Also, it's expected that the default `devServer` configuration "just works" and you need to modify `devServer` only in some rare cases, that's why a little knowledge of webpack is required.   

The message about starting re-bundle... We can include it, however, usually the re-build happens in just 1-2sec thus I don't know whether it makes a lot of sense.

**Comment by RickVanRousselt** [comment]
If this merge is accepted we can create a new issue for updating the docs. Would be a good first issue for someone to handle.

**Comment by pschaeflein** [comment]
On my project, the re-build takes more than 1-2 seconds. 

The completion is logged, but not the start.

The server side rebuild takes only a few seconds, and it logs. 


This PR is premature, IMO. The fact that we are still discussing how thing should work is a sign that the implementation may not be the best for all users of the tool. That is why I opened the discussion and made proposed changes there.

**Review by pschaeflein — COMMENTED** [review]
This PR is premature, IMO. 

The fact that we are still discussing how things should work is a sign that the implementation may not be the best for all users of the tool. That is why I opened the discussion and made proposed changes there.

**Comment by s-KaiNet** [comment]
Closing as it doesn't make sense to discuss any further here. Please refer to the great summary by @pschaeflein [here](https://github.com/pnp/generator-teams/discussions/248#discussioncomment-1459588)

**Pull request closed without merging**
