### PR TITLE
Added categories. Solves #109

### PR DESCRIPTION
**Pull request by appieschot**
Added categories. Solves #109

### CODE REVIEW

**Comment by wictorwilen** [comment]
Thanks. Can I suggest that we use the `prefix` property of the `inquirer` module so we get color-coded output like this: 
image
Instead of:
image

It will probably be easier to maintain as well, with a string property in each sub-generator

(ofc - use the brackets, I was just testing the differences).

**Comment by appieschot** [comment]
Totally makes sense, didn't think of using that. Let me update the PR.

**Comment by wictorwilen** [comment]
Also, would you mind adding this change to the change log?

**Comment by appieschot** [comment]
Overwriten the PR with new version; need a little guidance on the changelog though @wictorwilen do we release a new version for this change or do I update the 3.3.1 notes?

**Comment by wictorwilen** [comment]
@appieschot looks good! Please add an update on this under the *Changes* heading in the *Unreleased* version. Then we can release this as an updated preview of the current preview version

**Comment by appieschot** [comment]
> @appieschot looks good! Please add an update on this under the _Changes_ heading in the _Unreleased_ version. Then we can release this as an updated preview of the current preview version

Thanks! That makes total sense; updated PR (and fixed minor typo) didn't squash.

**Review by wictorwilen — APPROVED** [review]
Good to go!

**Pull request merged**
